version: '3.4'

services:

  rabbitmq:
      container_name: rabbit-studies-rabbitmq-dev
      image: rabbitmq:3-management
      hostname: localhost
      ports:
          - 5672:5672
          - 15672:15672
